### ISSUE TITLE
Automatic MONAI install

### ISSUE THREAD

**Issue by lassoan** [Project-MONAI/SlicerMONAIViz#11]
Instead of asking the user to install MONAI manually, we should display a confirmation popup: OK to install MONAI or cancel to install it manually.

**Comment by dzenanz** [comment]
This could be done similarly to https://github.com/fepegar/SlicerTorchIO/blob/c3fe328b3a940e2e2f11ea7735f5030153be7a4b/TorchIOModule/TorchIOModule.py#L64-L94

**Comment by lassoan** [comment]
It can wait, as the user can install using the Python console, but it would be a significant usability improvement.
Probably some time is needed for internal testing and small fixes and improvements so everything could come together in the next few weeks for a public announcement.

**Comment by dzenanz** [comment]
I am looking into this. Can someone assign the issue to me?
